import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, realpath, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

test('Edit project detects only present agent folders and saved selections control project instructions and skills', async t => {
  const directory = await realpath(await mkdtemp(join(tmpdir(), 'sector7-agent-folders-')));
  const data = join(directory, 'data'); const repo = join(directory, 'repo');
  await mkdir(join(repo, '.codex', 'skills', 'project-fact'), { recursive: true });
  await writeFile(join(repo, '.codex', 'AGENTS.md'), 'PROJECT_CODEX_INSTRUCTIONS');
  await writeFile(join(repo, '.codex', 'skills', 'project-fact', 'SKILL.md'), '---\nname: project-fact\ndescription: Project fact skill\n---\nPROJECT_SKILL_INSTRUCTIONS');
  await writeFile(join(repo, '.codex', 'auth.json'), 'PRIVATE_CONTENT_MUST_NOT_BE_READ');
  const previous = process.env.AI_GUI_DATA_DIR; const previousHome = process.env.HOME;
  const home = join(directory, 'home');
  await mkdir(join(home, '.codex', 'skills', 'project-fact'), { recursive: true });
  await writeFile(join(home, '.codex', 'skills', 'project-fact', 'SKILL.md'), 'HOME_SKILL_INSTRUCTIONS');
  await writeFile(join(home, '.codex', 'AGENTS.md'), 'HOME_AGENT_INSTRUCTIONS_NOT_AUTOMATICALLY_LOADED');
  process.env.AI_GUI_DATA_DIR = data; process.env.HOME = home;
  const { POST: folders } = await import('../../../app/api/local/folders/route');
  const { GET: skills, POST: snapshot } = await import('../../../app/api/local/skills/route');
  const { commitWorkspace, loadWorkspace } = await import('~/server/local/workspace');
  const { emptyWorkspace } = await import('./workspace-schema');
  const { useFolderStore } = await import('~/common/stores/folders/store-chat-folders');
  const { pauseDiskWrites } = await import('./disk-storage');
  const state = useFolderStore.getState();
  t.after(async () => { pauseDiskWrites(true); useFolderStore.setState(state); if (previous === undefined) delete process.env.AI_GUI_DATA_DIR; else process.env.AI_GUI_DATA_DIR = previous; if (previousHome === undefined) delete process.env.HOME; else process.env.HOME = previousHome; await rm(directory, { recursive: true, force: true }); });
  const request = (path: string, body?: unknown) => new Request(`http://localhost${path}`, { method: body === undefined ? 'GET' : 'POST', headers: { host: 'localhost', 'Content-Type': 'application/json' }, ...(body === undefined ? {} : { body: JSON.stringify(body) }) });
  const inspected = await folders(request('/api/local/folders', { action: 'inspect', path: repo }));
  assert.equal(inspected.status, 200);
  assert.deepEqual((await inspected.json()).agentFolders, ['codex']);
  pauseDiskWrites(true);
  useFolderStore.setState({ folders: [{ id: 'project', title: 'Project', instructions: '', fileIds: [], revision: 0, conversationIds: ['chat'], connectedFolders: [{ id: 'repo', name: 'Repo', path: repo }] }] });
  useFolderStore.getState().updateProject('project', { connectedFolders: [{ id: 'repo', name: 'Repo', path: repo, agentFolders: { codex: true, claude: false } }] });
  const workspace = emptyWorkspace();
  workspace.stores['app-folders'] = { version: 1, state: { folders: useFolderStore.getState().folders, enableFolders: true } };
  const { createDConversation } = await import('~/common/stores/chat/chat.conversation');
  const { _abortController, ...chat } = createDConversation(); chat.id = 'chat';
  workspace.stores['app-chats'] = { version: 5, state: { conversations: [chat] } };
  await commitWorkspace(workspace, 0, data);
  const catalogResponse = await skills(request('/api/local/skills?origin=codex&conversationId=chat'));
  assert.equal(catalogResponse.status, 200);
  const catalog = await catalogResponse.json();
  assert.deepEqual(catalog.instructions, ['PROJECT_CODEX_INSTRUCTIONS']);
  const entries = catalog.skills.filter((skill: { name: string }) => skill.name === 'project-fact');
  assert.equal(entries.length, 2); assert.notEqual(entries[0].id, entries[1].id);
  const entry = entries.find((skill: { scope: string }) => skill.scope === 'project'); assert.ok(entry);
  const selected = await snapshot(request('/api/local/skills', { id: entry.id, conversationId: 'chat' }));
  assert.equal(selected.status, 200);
  assert.match((await selected.json()).skill.instructions, /PROJECT_SKILL_INSTRUCTIONS/);
  assert.doesNotMatch(JSON.stringify(catalog), /PRIVATE_CONTENT_MUST_NOT_BE_READ/);
  const saved = (await loadWorkspace(data)).workspace!;
  const projects = saved.stores['app-folders']!.state.folders as typeof state.folders;
  assert.deepEqual(projects[0].connectedFolders![0].agentFolders, { codex: true, claude: false });
  projects[0].connectedFolders![0].agentFolders = { codex: false, claude: false };
  await commitWorkspace(saved, saved.revision, data, saved.revisionEpoch);
  const disabled = await (await skills(request('/api/local/skills?origin=codex&conversationId=chat'))).json();
  assert.deepEqual(disabled.instructions, []);
  assert.equal(disabled.skills.some((skill: { id: string }) => skill.id === entry.id), false);
  assert.equal((await snapshot(request('/api/local/skills', { id: entry.id, conversationId: 'chat' }))).status, 404);
  const outside = await (await skills(request('/api/local/skills?origin=codex&conversationId=outside'))).json();
  assert.deepEqual(outside.instructions, []);
  assert.equal(outside.skills.some((skill: { id: string }) => skill.id === entry.id), false);
  assert.equal((await snapshot(request('/api/local/skills', { id: entry.id, conversationId: 'outside' }))).status, 404);
  assert.equal((await skills(request('/api/local/skills?origin=codex&conversationId=../x'))).status, 400);
  await mkdir(join(repo, '.claude'));
  await writeFile(join(repo, '.claude', 'CLAUDE.md'), 'PROJECT_CLAUDE_INSTRUCTIONS');
  await writeFile(join(repo, '.codex', 'config.toml'), 'PRIVATE_CONFIG_MUST_NOT_BE_READ');
  await writeFile(join(repo, '.claude', 'settings.json'), 'PRIVATE_SETTINGS_MUST_NOT_BE_READ');
  const both = await folders(request('/api/local/folders', { action: 'inspect', path: repo }));
  assert.deepEqual((await both.json()).agentFolders, ['codex', 'claude']);
  const enabled = (await loadWorkspace(data)).workspace!;
  const enabledProjects = enabled.stores['app-folders']!.state.folders as typeof state.folders;
  enabledProjects[0].connectedFolders![0].agentFolders = { codex: true, claude: true };
  await commitWorkspace(enabled, enabled.revision, data, enabled.revisionEpoch);
  const claude = await (await skills(request('/api/local/skills?origin=claude&conversationId=chat'))).json();
  assert.deepEqual(claude.instructions, ['PROJECT_CLAUDE_INSTRUCTIONS']);
  assert.doesNotMatch(JSON.stringify(claude), /PROJECT_CODEX_INSTRUCTIONS|PRIVATE_SETTINGS/);
  const codex = await (await skills(request('/api/local/skills?origin=codex&conversationId=chat'))).json();
  assert.deepEqual(codex.instructions, ['PROJECT_CODEX_INSTRUCTIONS']);
  assert.doesNotMatch(JSON.stringify(codex), /PROJECT_CLAUDE_INSTRUCTIONS|PRIVATE_CONFIG/);
  await writeFile(join(repo, '.codex', 'AGENTS.md'), 'x'.repeat(256 * 1024 + 1));
  assert.equal((await skills(request('/api/local/skills?origin=codex&conversationId=chat'))).status, 413);
});
